services:
  db:
    image: postgres:16
    container_name: myapp-postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '5432:5432' # 호스트 5432 ↔ 컨테이너 5432
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -d ${DB_DATABASE} -U ${DB_USERNAME} || exit 1',
        ]
      interval: 5s
      timeout: 3s
      retries: 30
volumes:
  db_data:
